# Generated by Django 5.1.7 on 2025-03-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipgetter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='isp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
