# Generated by Django 5.1.7 on 2025-03-22 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipgetter', '0002_user_city_user_country_user_isp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_ip',
            new_name='ip_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
    ]
